# Generated by Django 4.1.3 on 2022-12-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream_space', '0003_user_shops_alter_shop_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('BAT', 'Bathroom'), ('BED', 'Bedroom'), ('KIT', 'Kitchen'), ('LIV', 'Living room'), ('GAR', 'Garden'), ('COR', 'Corridor'), ('OTH', 'Other')], max_length=3)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dream_space.shop')),
            ],
        ),
    ]
