# Generated by Django 4.1.3 on 2022-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_space', '0007_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
